language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls"
script:
  - ./scripts/run-tests.sh
after_success:
  - coveralls
