language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - ./setuptests.sh
install:
  - "pip install -r requirements.txt --use-mirrors"
script:
  - python manage.py syncdb
  - python manage.py migrate
  - python manage.py test
